---
version: '3.8'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.5.1
    ports:
      - '32181:32181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000


  kafka-1:
    image: confluentinc/cp-kafka:5.5.1
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: ../Dockerfile.springboot
    image: client-gateway
    ports:
    - 8080:8080
    depends_on:
      - kafka-1
    container_name: client-gateway
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.kafka.bootstrap-servers": "kafka-1:29092"
      }'

  settlement-manager:
    build:
      context: ./settlement-manager
      dockerfile: ../Dockerfile.springboot
    image: settlement-manager
    ports:
    - 8081:8081
    depends_on:
      - kafka-1
    container_name: settlement-manager
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.kafka.bootstrap-servers": "kafka-1:29092"
      }'

