#
#     Copyright (C) 2021  Divisible By Zero
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as published
#     by the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#

spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: som-testing
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              # can wildcard, but should really list our specific model packages
              packages: '*'
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  servlet:
    contextPath: /api/
  error:
    include-message: always

som:
  ui:
    url: http://localhost:4200
  settlement-manager:
    kafka:
      topic:
        request: settlement-manager.request
        response: settlement-manager.response
